### PR TITLE
"Quest Log Levels" option improvement

### PR DESCRIPTION
**Pull request by anzz1**
- Show elite/dungeon/raid/group quests with +

### CODE REVIEW

**Comment by anzz1** [comment]
Further improvements to be considered, not featured in this PR:

- Adding quest level to the quest detail frame
Caveat: By default, quest level is only available when the detail frame (QuestInfoFrame) is opened from quest log. When opened from a gossip or non-gossip quest NPC, level is not available, only quest ID. AFAIK there is no way to get quest level from quest ID without resorting to outside help like Questie's database.

- Adding quest level to npc gossip options
Caveat: Quest name & level is available here, but quest ID is not, so tag info whether it's a elite/dungeon/raid/group quest is not available. This could be retrieved using a reverse search by quest name from Questie's database, but as there probably are quests with the same name, this isn't a great option.

So with my current knowledge, these options shouldn't be added as-is but if something surfaces to get around the caveats, they could be revisited. Here's the code for how far I got before running into a wall, for safe keeping.

```lua
-- Show quest level in quest detail frame
hooksecurefunc(QuestInfoTitleHeader, "SetWidth", function()
    if (QuestInfoFrame.questLog) then
        local quest = GetQuestLogSelection()
        if quest then
            local title, level, _, _, _, _, _, questId = GetQuestLogTitle(quest)
            if title and level and questId then
                QuestInfoTitleHeader:SetText(getQuestLevelString(level, questId) .. title)
            end
        end
    elseif (QuestieLib) then
        local title = GetTitleText()
        if (title) then
            local questId = GetQuestID()
            if (questId) then
                local level = QuestieLib:GetTbcLevel(questId)
                if (level) then
                    local s = QuestieLib:GetLevelString(questId, _, level, true)
                    if (s) then
                        QuestInfoTitleHeader:SetText(s .. title)
                    end
                end
            end
        end
    end
end)

-- Show quest levels in gossip frame
hooksecurefunc("GossipFrameUpdate", function()
    local buttonIndex = 1

    -- name, level, isTrivial, isDaily, isRepeatable, isLegendary, isIgnored, ... = GetGossipAvailableQuests()
    local availableQuests = {GetGossipAvailableQuests()}
    local numAvailableQuests = table.getn(availableQuests)
    for i=1, numAvailableQuests, 7 do
        local titleButton = _G["GossipTitleButton" .. buttonIndex]
        local title = "["..availableQuests[i+1].."] "..availableQuests[i]
        local isTrivial = availableQuests[i+2]
        if isTrivial then
            titleButton:SetFormattedText(TRIVIAL_QUEST_DISPLAY, title)
        else
            titleButton:SetFormattedText(NORMAL_QUEST_DISPLAY, title)
        end
        GossipResize(titleButton)
        buttonIndex = buttonIndex + 1
    end
    if numAvailableQuests > 1 then
        buttonIndex = buttonIndex + 1
    end

    -- name, level, isTrivial, isDaily, isLegendary, isIgnored, ... = GetGossipActiveQuests()
    local activeQuests = {GetGossipActiveQuests()}
    local numActiveQuests = table.getn(activeQuests)
    for i=1, numActiveQuests, 6 do
        local titleButton = _G["GossipTitleButton" .. buttonIndex]
        local title = "["..activeQuests[i+1].."] "..activeQuests[i]
        local isTrivial = activeQuests[i+2]
        if isTrivial then
            titleButton:SetFormattedText(TRIVIAL_QUEST_DISPLAY, title)
        else
            titleButton:SetFormattedText(NORMAL_QUEST_DISPLAY, title)
        end
        GossipResize(titleButton)
        buttonIndex = buttonIndex + 1
    end
end)
```

**Comment by anzz1** [comment]
The way you implemented it using the suggestedGroup member of GetQuestLogTitle instead of questID->GetQuestTagInfo is even better. Good work.

**Comment by leatrix** [comment]
The latest alpha shows quest levels in the quest detail pane for quests in your quest log.  It shows when you open your quest log and when you click a quest in the objective tracker.  It doesn't show when you accept or turn-in a quest.

Quest difficulty levels are always shown in the quest detail pane alongside quest levels and there is a new setting to toggle quest difficulty levels in the quest log list (because some people want to see the difficulty level in the quest log list while others prefer not to because it indents the quest title column).

**Comment by anzz1** [comment]
Maybe add a extra space so the title columns are not staggered?
Like this
```
[70]  For The Horde!
[70+] For The Horde!
```

**Comment by anzz1** [comment]
One thing I'd like to add though, is style option for Blizzlike (+) and detailed (D/R/P/+)

**Pull request closed without merging**
